[project]
name = "mvis-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.136.1",
    "monai>=1.5.2",
    "nibabel>=5.4.2",
    "opencv-python>=4.13.0.92",
    "torch>=2.11.0",
    "uvicorn>=0.46.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.0",
    "pytest>=9.0.3",
    "ruff>=0.15.12",
]
