[project]
name = "mvis-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.136.1",
    "fsspec>=2026.4.0",
    "monai>=1.5.2",
    "nibabel>=5.4.2",
    "opencv-python>=4.13.0.92",
    "orjson>=3.11.9",
    "torch>=2.11.0",
    "universal-pathlib>=0.3.10",
    "uvicorn>=0.46.0",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pre-commit>=4.6.0",
    "pytest>=9.0.3",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.15.12",
]
